spring.output.ansi.enabled: ALWAYS
#spring.autoconfigure.exclude:
#  - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
#  - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: testSpring