spring:
  data:
    mongodb:
#      host: localhost
#      port: 27017
#      database: testSpring
      uri: mongodb+srv://mongouser:${mongodb.password}@cluster0.xecpsrk.mongodb.net/testSpring
  output.ansi.enabled: ALWAYS